<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'monolog.handler.GmoPaymentGateway4' shared service.

include_once $this->targetDirs[3].'\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\FingersCrossedHandler.php';

$this->services['monolog.handler.GmoPaymentGateway4'] = $instance = new \Monolog\Handler\FingersCrossedHandler(${($_ = isset($this->services['monolog.handler.GmoPaymentGateway4_rotating_file']) ? $this->services['monolog.handler.GmoPaymentGateway4_rotating_file'] : $this->load('getMonolog_Handler_GmoPaymentGateway4RotatingFileService.php')) && false ?: '_'}, 400, 0, true, true, 200);

$instance->pushProcessor(${($_ = isset($this->services['monolog.processor.psr_log_message']) ? $this->services['monolog.processor.psr_log_message'] : ($this->services['monolog.processor.psr_log_message'] = new \Monolog\Processor\PsrLogMessageProcessor())) && false ?: '_'});

return $instance;
