<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.gfmsrh3' shared service.

return $this->services['service_locator.gfmsrh3'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['session' => function () {
    return ${($_ = isset($this->services['session']) ? $this->services['session'] : $this->getSessionService()) && false ?: '_'};
}]);
