<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2jafudq\EccubeProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2jafudq/EccubeProdProjectContainer.php') {
    touch(__DIR__.'/Container2jafudq.legacy');

    return;
}

if (!\class_exists(EccubeProdProjectContainer::class, false)) {
    \class_alias(\Container2jafudq\EccubeProdProjectContainer::class, EccubeProdProjectContainer::class, false);
}

return new \Container2jafudq\EccubeProdProjectContainer([
    'container.build_hash' => '2jafudq',
    'container.build_id' => 'c14bb3ea',
    'container.build_time' => 1590787731,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2jafudq');
