<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'Plugin\Securitychecker4\Form\Type\Securitychecker4ConfigType' shared autowired service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormTypeInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\AbstractType.php';
include_once $this->targetDirs[3].'\\app\\Plugin\\Securitychecker4\\Form\\Type\\Securitychecker4ConfigType.php';

return $this->services['Plugin\\Securitychecker4\\Form\\Type\\Securitychecker4ConfigType'] = new \Plugin\Securitychecker4\Form\Type\Securitychecker4ConfigType();
